### ISSUE TITLE
Review of about wiki

### ISSUE THREAD

**Issue by sequomics** [sequomics/rose#3]
Hey, If you have free or enough time please review this wiki.
Refer link: [About] (https://github.com/sequomics/rose/wiki)

Thanks.

**Comment by marianelagrande** [comment]
HI! Good morning and good Sunday!!
I have been reading all the texts (about and readme) and both are fine and
I could understand everything that you've written so I thank thats is more
than fine hahah. I didn't see any wrong word, so great job!!!!

Enjoy your day!!!

2015-02-15 9:40 GMT+01:00 sequomics <notifications@github.com>:

> Assigned #3 <https://github.com/sequomics/rose/issues/3> to
> @marianelagrande <https://github.com/marianelagrande>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequomics/rose/issues/3#event-235948383>.
>



-- 
Marion
www.mariondesigntogo.com
Lunes a viernes: 9-13hs y 16-20hs
Monday to Friday: 9-13hs & 16-20Hs

**Comment by sequomics** [comment]
Hi dear,
Good to see you on GitHub. Now, i think you feeling more comfortable and confident.
I am also doing the updates of Wiki. I am online here.

So, you can check and review if you want, simultaneously.

Thanks,
Enjoy Sunday,
Prabhat Kumar.

**Comment by sequomics** [comment]
Hi dear,
If you have some free time from your busy schedule, have a final look for the same.
And, you can "Close" this issue after putting some valuable comments.

Now, i have given you the authority to do so.

Have nice Sunday,
Cheers,
Prabhat Kumar.

**Comment by marianelagrande** [comment]
Hi, I think that the text and the concept are fine, you give the people all
the necessary information to know about rose. I think that Rose will go to
work very well.

Thanks for giving me this opportunity.

Cheers!

2015-02-15 13:28 GMT+01:00 sequomics <notifications@github.com>:

> Hi dear,
> If you have some free time from your busy schedule, have a final look for
> the same.
> And, you can "Close" this issue after putting some valuable comments.
>
> Now, i have given you the authority to do so.
>
> Have nice Sunday,
> Cheers,
> Prabhat Kumar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequomics/rose/issues/3#issuecomment-74415471>.
>



-- 
Marion
www.mariondesigntogo.com
Lunes a viernes: 9-13hs y 16-20hs
Monday to Friday: 9-13hs & 16-20Hs

**Comment by sequomics** [comment]
Hi, Dear,
Indeed, it is a great contribution from you. I hope, we will work together to release this project to the community.

Many thanks for your every effort.

Now, i am closing this issue on behalf of you.

Great Participation from You.
Enjoy & Take Care,
Prabhat Kumar
